<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>450eb80e-4937-412a-b56a-e2c937d6a9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.el-button.btn-block.btn-login-form.el-button--primary.el-button--medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1478220c-e57e-4ff4-9877-fada885951e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e38b2581-16c8-4cc0-ac15-034fe7f96dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button btn-block btn-login-form el-button--primary el-button--medium</value>
      <webElementGuid>6a725c53-fd7c-49c7-9113-e0ad00dbd1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Masuk
          </value>
      <webElementGuid>2ea6330c-f2e6-4b0c-b296-397759e9b195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-page transition-start&quot;]/div[@class=&quot;container-login-page&quot;]/div[@class=&quot;login-form&quot;]/form[@class=&quot;el-form&quot;]/div[@class=&quot;el-form-item el-form-item--medium&quot;]/div[@class=&quot;el-form-item__content&quot;]/button[@class=&quot;el-button btn-block btn-login-form el-button--primary el-button--medium&quot;]</value>
      <webElementGuid>e4ee4188-3430-418d-9465-e1ea8d80553a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>edaf2b63-fde2-4185-b7e2-e2eb51d77b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/div[3]/div/button</value>
      <webElementGuid>6776ecab-5bff-4ce6-b300-008c6084e49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[2]/following::button[1]</value>
      <webElementGuid>95fd5033-c3b7-46b6-bec6-c7e35be3a25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[1]/following::button[1]</value>
      <webElementGuid>4316b072-19d7-4b06-a9aa-82b5e15c1707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum terdaftar?'])[1]/preceding::button[1]</value>
      <webElementGuid>4fd3eec6-996b-4606-ac89-9410495865c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>cad473ab-87b4-4686-b1f8-32a6a006a652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
            Masuk
          ' or . = '
            Masuk
          ')]</value>
      <webElementGuid>adfac514-7295-4f6e-9e7d-7a88b52b181a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
